# These are supported funding model platforms

github: ToQuery # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: ToQuery # Replace with a single Patreon username
open_collective: ToQuery # Replace with a single Open Collective username
ko_fi: ToQuery # Replace with a single Ko-fi username
tidelift: npm/babel # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: CleverWeb # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: # Replace with a single custom sponsorship URL
