language: java


jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'node'
    - 'node_modules'

install:
  - mvn install -DskipTests -X

script:
  - mvn clean package -DskipTests -X