app:
  security:
    whitelist: /h2-console/**
  jwt:
    secret: 123456
  page:
    param:
      page-size: ps


spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev