app:
  security:
    whitelist:
      - /
      - /index.html
      - /static/**
      - /error
      - /h2-console/**
      - /app/ueditor
      - /app/files/download
  jwt:
    secret: 123456
    expiration: 6000
  page:
    param:
      page-size: ps


spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: "200MB"
      maxRequestSize: "200MB"
