app:
  security:
    whitelist:
      - /
      - /management/**
      - /manifest.webapp
      - /index.html
      - /static/**
      - /error
      - /h2-console/**
      - /app/files/download
      - /example/**
      - /content/**
      - /favicon.ico
      - /test/**
  jwt:
    secret: 123456
    expiration: 6000
  page:
    param:
      page-size: ps

  files:
    show-domain: http://127.0.0.1

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'logfile', 'loggers', 'prometheus', 'threaddump']
  endpoint:
    health:
      show-details: when-authorized
      roles: 'ROLE_ADMIN'
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  metrics:
    export:
      # Prometheus is the default metrics backend
      prometheus:
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        auto-time-requests: true



spring:
  application:
    name: CleverWeb
  thymeleaf:
    mode: HTML
  output:
    ansi:
      console-available: true
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  servlet:
    multipart:
      maxFileSize: "200MB"
      maxRequestSize: "200MB"
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    root: warn
    org.springframework: warn
    org.springframework.security: trace
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: debug
    io.github.toquery: debug
