
spring:
  datasource:
    # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/clever_web?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect #使用innodb引擎

logging:
  level:
    root: info
    org.springframework.security: debug
    io.github.toquery.framework: debug


server:
  port: 8081
  servlet:
    context-path: /api
