app:
  security:
    whitelist:
      - /
      - /index.html
      - /static/**
      - /error
      - /h2-console/**
      - /app/ueditor
      - /app/files/download
  jwt:
    secret: 123456
    expiration: 6000
  page:
    param:
      page-size: ps

  files:
    show-domain: http://127.0.0.1
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: "200MB"
      maxRequestSize: "200MB"
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
