
spring:
  datasource:
    url: jdbc:mysql://mysql.jszx.sparke.cn:3306/cleverweb_mgr?autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: spark2016
  jpa:
#    hibernate:
#      ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8899

logging:
  level:
    root: info