app:
  security:
    whitelist:
      - /
      - /manifest.webapp
      - /index.html
      - /static/**
      - /error
      - /h2-console/**
      - /app/ueditor
      - /app/files/download
      - /example/**
      - /favicon.ico
      - /test/**
  jwt:
    secret: 123456
    expiration: 6000
  page:
    param:
      page-size: ps

  files:
    show-domain: http://127.0.0.1

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  servlet:
    multipart:
      maxFileSize: "200MB"
      maxRequestSize: "200MB"
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    root: debug
    org.springframework: debug
    org.springframework.security: trace
    io.github.toquer: debug
