

spring:
  datasource:
    url: jdbc:h2:mem:clever_web
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

logging:
  level:
    root: info
    org.springframework.security: debug
    io.github.toquery.framework.security: debug



server:
  port: 8081
